server:
  h2:
    console:
      enabled: true
      path: /h2-console

github:
  scope: repo
  client-id: ff9faee8767641f7d7e1

spring:
  profiles:
    active: local
  datasource:
    platform: org.hibernate.dialect.H2Dialec
    # url: jdbc:h2:file:./devears;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:mem://localhost/devears;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      apache:
        http: DEBUG
    httpclient:
      wire: DEBUG
